/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fa(a, b, cin, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output s;
  wire s;
  assign _02_ = b ^ a;
  assign s = _02_ ^ cin;
  assign _03_ = b & a;
  assign _04_ = cin & b;
  assign _00_ = _04_ | _03_;
  assign _01_ = cin & a;
  assign cout = _01_ | _00_;
endmodule
